### ISSUE TITLE
I receive an error for <<something>> in mdx

### ISSUE THREAD

**Issue by talatkuyuk** [silvenon/remark-smartypants#71]
I am using `next-mdx-remote` for mdx in my `nextjs` project. It uses `@mdx-js/mdx` under the hood.

I receive an error for `<< something>>` in the mdx. The other features work fine in the plugin `remark-smartypants`.

```mdx
test.. test... test..... test?..... test!....  
!!!!!! ???? ,, - -- ---  
"Smartypants, double quotes" and 'single quotes'
en dash (--), em dash (---)
# <<Hello World!>>
```
![EF1DC554-79BB-4399-AF0A-2F0CC14764A8](https://user-images.githubusercontent.com/30029208/210136227-af32da5e-ad48-42bb-b51f-a8a2bbc057cb.jpeg)

**Comment by silvenon** [comment]
My readme suggested that it's possible, but I don't think it is because angle quotes are invalid syntax in MDX. I updated the readme to mention that.

I'm glad to hear that other features are working fine, though.

**Comment by talatkuyuk** [comment]
I digged the issue, after closing.

I realized that, the cause is `@mdx-js/mdx`. Because it expects **an option** for `format`, the default is `mdx`. In the code of `@mdx-js/mdx` I found that: [link](https://github.com/mdx-js/mdx/blob/main/packages/mdx/lib/core.js#L103)

```js
const pipeline = unified().use(remarkParse)

if (format !== 'md') {
  pipeline.use(remarkMdx) // which is "remark-mdx"
}

pipeline
  .use(remarkMarkAndUnravel)
  .use(remarkPlugins || [])
  ...
```
Means that, `remark-mdx` comes prior to `remarkPlugins` and used just after `remark-parse`, and this causes the issue.

If the `remark-mdx` would used after the  `remarkPlugins` there would be no problem.
