### ISSUE TITLE
curly quotes go the wrong way before a link

### ISSUE THREAD

**Issue by sophiebits** [silvenon/remark-smartypants#74]
If I run the following

```js
import { remark } from 'remark'
import smartypants from 'remark-smartypants'

const result = await remark()
  .use(smartypants)
  .process('"wow". go to "[google](https://www.google.com/)" today.')

console.log(String(result))
```

the output is:

```
“wow”. go to ”[google](https://www.google.com/)” today.
```

Note that the curly quote before the `google` link goes the wrong way – it's a closing quote but should be an opening one.

**Comment by silvenon** [comment]
Hey, thanks for the bug report! This remark plugin is currently incredibly naive, i.e. essentially a hack, so bugs like this are going to show up. I'm out of the open source game for quite a while, unfortunately, but I would very much like this plugin to be smarter. If you'd like to take a stab at this bug I'll be around for code review!

**Comment by ghost** [comment]
Experiencing this bug as well. Context is something like this...
```md
"**Bolded part** of this quote"
```
Where the output's left quotation mark is closing, and should be opening. Removing the `**` or moving it to outside the quotation marks fixes the issue, but isn't grammatically correct since the bold is only part of the quote.

**Comment by dimaMachina** [comment]
@sophiebits @silvenon @gene-fls I fixed both cases with a tiny solution 🎉

**Comment by 2wheeh** [comment]
Hi guys !
It also happens around `inlineCode`:

```md
"`code` foo"
```
I will add some comments on #80

**Comment by dimaMachina** [comment]
@2wheeh ty for new case, fixed this too!

**Comment by silvenon** [comment]
Your bug reports and fixes rock the house, thanks to you we'll get this released in no time 💪
